[storage]
working_dir = "ordhook"

# The Http Api allows you to register / deregister
# dynamically predicates.
# Disable by default.
#
# [http_api]
# http_port = 20456

[network]
mode = "mainnet"
bitcoind_rpc_url = "http://0.0.0.0:8332"
bitcoind_rpc_username = "1"
bitcoind_rpc_password = "1"
# Bitcoin block events can be received by Chainhook
# either through a Bitcoin node's ZeroMQ interface,
# or through the Stacks node. Zmq is being
# used by default:
bitcoind_zmq_url = "tcp://0.0.0.0:18543"
# but stacks can also be used:
# stacks_node_rpc_url = "http://0.0.0.0:20443"

[resources]
ulimit = 2048
cpu_core_available = 2
memory_available = 1
bitcoind_rpc_threads = 8
bitcoind_rpc_timeout = 30
expected_observers_count = 1


# Disable the following section if the state
# must be built locally
[snapshot]
#download_url = "https://archive.hiro.so/mainnet/ordhook/mainnet-ordhook-sqlite-latest"

[logs]
ordinals_internals = true
chainhook_internals = true

[http_api]
http_port = 20456
database_uri = "redis://localhost:6379/"

[limits]
max_number_of_bitcoin_predicates = 8
max_number_of_concurrent_bitcoin_scans = 8
max_number_of_processing_threads = 8
bitcoin_concurrent_http_requests_max = 8
max_caching_memory_size_mb = 1
